import { Component } from '@angular/core';
import { MihttpService } from '../mihttp.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-registro',
  templateUrl: './registro.component.html',
  styleUrls: ['./registro.component.css']
})
export class RegistroComponent {

  error: string;

  constructor(private http: MihttpService, private router: Router) { 
    this.error = ""
  }

  public registro(correo: string, contraseña: string, nombre: string, direccion: string){

    var body = {
      correo: correo,
      contraseña: contraseña,
      nombre: nombre,
      foto: "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAGPAY8DASIAAhEBAxEB/8QAGwABAAMBAQEBAAAAAAAAAAAAAAQFBgMCAQf/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEAMQAAAB/UQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjElUx6vmdGiUMgtkaTAAAAAAAAAAAAAAAAAAADj4oqkRBAAAEuINH2zN6skQAAAAAAAAAAAAAAAA5daKo3gQAAAAB78DSdaO8lAAAAAAAAAAAAAAAAj56xrrAAAAAAAGhz1iXAlAAAAAAAAAAAAAAHMz/IsAAAAAAAdeQ1Ln0lAAAAAAAAAAAAAARZUCqUIAAAAAAABfyoM5QgAAAAAAAAAAAABXWNbVQEAAAAAAAAuLGtslCAAAAAAAAAAAAAFdYw6oggAAAAAAAFxYw5ihAAAAAAAAAAAAADl1GWSY1gAAAAAAAkl31JQAAAAAAAAAAAAAAIdFqaqqsIAAAAAAvY1qoQAAAAAAAAAAAAAAABDqtCrLNHGSlWngrlgK9Y+yrXUkpLSaUIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYkqiLWg5Z34aFnho+uX+moZ6UW6NJgAAAAAAAAAAAAAAAAcjrCrolSI4gAAAACRHF5Ny0tb5z6QAAAAAAAAAAAAAIR6pPPywAAAAAAAAD3d0P01CFNlAAAAAAAAAAAHM40PrxYAAAAAAAAAAB9vqD2aZz6SgAAAAAAAAAKKwo6BAAAAAAAAAAAAJl7lrxZogAAAAAAAARSojlgAAAAAAAAAAAACRHGpRZUoAAAAAAACmuc1XMIAAAAAAAAAAAAABYXOa0qhAAAAAAAHHOXlHQIAAAAAAAAAAAAAA0ecvFmiAAAP/EACcQAAIBBAEDBAIDAAAAAAAAAAIDAQAEEkBQERMwFCEjMiIzIHCQ/9oACAEBAAEFAv8ADs3AFFdTUvZXdOu6dQ9lDdTQOA+JYwVw1xH4VOIKWwWRwrm9uCKSnxCUjKW9yODYcAJTJT5BmRlZwY8FcsyPzWzMD4F54L0EHmvgLwvy0LMvy4Bk5HoLnE99k9A0lz1DeuZ+HStp6p3rz9elZ/r3r366Vl9d69+ulZfXevfppWX03ruPh0rSPh3mxkvSVGK9944s0EDkzgLleY6FsvAeBuEee3TwjUCdGow8YKM6UgQ4clAVTahXpa9KVelOvSnXpSr0tRahQqAf6Pmeld0K7y67y67oVE9eKNwDRXU0TTL+cNMaG6mgcBcKy4EaNpH5QaQUu4EuBM4CGuI9FTiClnBxuudC6IpKdISkZS6Gbj3YVPvqx7Vbuz2nt7cT7zrR7ShvcjXYUAJlJFsAUiSygx1rhmZ7VuzA9W5PENy2ZkGo482biTwZp3BYr3rY8laV4XU96zLoekc5HvBOJ6Lp6K4BM9VaF3PxcBafp8H/xAAUEQEAAAAAAAAAAAAAAAAAAACQ/9oACAEDAQE/ARx//8QAFBEBAAAAAAAAAAAAAAAAAAAAkP/aAAgBAgEBPwEcf//EACoQAAECBQIGAQUBAAAAAAAAAAEAQAIRITFQMlESIjBBYXGRIGBwgaGQ/9oACAEBAAY/Av8ADu/wuWFXWorUVdc0Kv8AOJqth0dwqYbypnpzC84SZUz1ZhTGDl2HXl2OCLEb4EQ7MTDvgYixhOAiPhnCfD8sw/Htn+38LOJ/Czifj2zPv7RiDOEYA/LEYGlwxrc4Lig6/FHhJihVR06Cm6manD1hVJrV/FcK8KvCrhav4qzVIfwfVagtS1LUFTFXn6XKFWI/XSIrmCvL3haVKqerQqtDgZxLYMdwpwvpXKmWcwpWLyUOpVa0UotTql3NbuJlTLmYUw38B34LaQuXsu4ak9noLQ7mj8bijPh2f8O7Ml+CyiOBhOb/AP/EACoQAQAABQMDAwMFAAAAAAAAAAEAESExQFBRcTBBYYGhwbHR8SBwkJHw/9oACAEBAAE/If4O75M7QRYOWFbeCFfvQH9+Bb+SBWHhi2SO2kpgdexFGn4To0afhYmB17mjBuuxCNZvTBrJgtk3NEZ+lDt6vVNvUgn62h0ptnXqLbdCnIu0MGcGyjoM0jZXBksbKaDtquDtqOgeHE4flybPleXD/uf1z1Iv8vhqbNvsz/dYfus/3GH7jPFfDCvnpidmeHIDuzz/ACgYfhA0CXuzRgy92Kug1HdYNZ0JNNLk67zC4NFx9sdzp+8JbSMO03NoZcYX2iezF+Uj8pG7EPvES5xabm/7HhcCJHxsO1g2sTPnYC4OlXedtVDbB5Y+hCkLOr+kZVI+tCsFsPkizzNqNFnJ8aHrBsdV64bMUn4+gz+cRTThwaK8LE3HOcRJwwzWbhk1kwRNw5hG8vaEpalxUoaEgD2nvlUm7aEotVx0glEik2b5CntQivOSCvECe9j0o8WXSnzanx1ttYvpQM3aiziU9sM+pNxhyEdlc+Yrsph+e2ef47Z4XDGg8MYMhm7LQVMGzLo//9oADAMBAAIAAwAAABD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A++OPN/8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wDgf/8A/wC9D/8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/APz/AP8A/wD/AP8A1v8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AH//AP8A/wD/AP8Av/8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD+j/8A/wD/AP8A/wD/ANT/AP8A/wD/AP8A/wD/AP8A/wD/APo//wD/AP8A/wD/AP8AU/8A/wD/AP8A/wD/AP8A/wD/AP8A6P8A/wD/AP8A/wD/AP1P/wD/AP8A/wD/AP8A/wD/AP8A/wD/AH//AP8A/wD/AP8Av/8A/wD/AP8A/wD/AP8A/wD/AP8A/wD3P/8A/wD/AP8A+z//AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wA3P/PfN3//AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP74UOo03/8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/APs//wD/AP8A/wD/ADf/AP8A/wD/AP8A/wD/AP8A/wD/AL3/AP8A/wD/AP8A/wD/AO9//wD/AP8A/wD/AP8A/wD/ALf/AP8A/wD/AP8A/wD/AP8A+/f/AP8A/wD/AP8A/wD/APs//wD/AP8A/wD/AP8A/wD/AP8Ac/8A/wD/AP8A/wD/AP7f/wD/AP8A/wD/AP8A/wD/AP8A/v3/AP8A/wD/AP8A/wDs/wD/AP8A/wD/AP8A/wD/AP8A/wD/ANz/AP8A/wD/AP8A/wD7/wD/AP8A/wD/AP8A/wD/AP8A/wD/APv/AP8A/wD/xAAdEQACAgIDAQAAAAAAAAAAAAABEQAwQFAgYHAh/9oACAEDAQE/EPCHHHrTQOhGoXmoXmodG+7Bxxxx+GHAFJwBx//EABsRAAICAwEAAAAAAAAAAAAAAAERADAQQHBQ/9oACAECAQE/EOEKKLiAqN4qPkvceX5yiwouGDQNI1f/xAArEAABAQcCBgMAAwEAAAAAAAABEQAhMUBBUWFQcYGRobHB4TDR8BAgcJD/2gAIAQEAAT8Q/wCHZIhPzH6Y4gi63QQ5sfo2B/CKBMKfxAxpBF0uh+2JAL+I/WkmGMYliJHqrf4SIMuVbMIZxiNGNmiauePxmrjg1n32aIRSDguWXMRvlTMQmI5FwWOhqZXiAqan5zALcKGh0JQyc7PpZFTXcx6TQYWCgZPpJGFgoGR6XQU0LymyukV0Liuyv0BJIiN0k1kiIt0nzJokB1HuTIpoQ6p84Sory9JM12U5T40FQl29yZqKiO3qfXhVJrwon17BHSTTuEdJ/FH4eZPNH4eJ8oGJQBmnaTKRiEEZr30BPg+4BkTlg+4QMNBdcrklRbsyUkCjGj8g0FtCIIC9Rv4j5wMgP3OiENwIgWUFCOcfGiEwLD+bMVCNEmA2GjkiSSaHjxDPDCqE7M/cMH2aqu6jwx9g+mHsH0wMr7hT4Z244HszwwqhOzEgQSKnhxP+HilC3JRiU/gB7MAqsEIjAKdwAd2FKFuCukrdlwIP4UZyDdwsqc08GIShJN39/wCpCUIIs7syZzTyZyDdgsmhV/CjLbQ1u3LmlxjYHLjH7f5RYHDnH7ZusRFx+2W2gOoTRUsUJjb1kTAJ0oM8psqJ6JB5d2JXPJkrjaBB59pw5IijQbsUpQplSlKFDBJAOgmgRwblssUNUpMuUNUoLAhg3L5mIbkAubMRV8pxMkVfKMtDciFjaWcAz8wXORvNvzAc4G7OIlX/ACOAbC86+uqNxSU3cxgRc5Y/LOkLl88E/hybZ8m+ROoT7xF6BJqkctuPpJ9Ujltw9LJEpF1WXZUOG1u0+myoMtrd2GHyJFp4MA5Lh1I0Ei08iCchx6gyOLPy8aCuFfy8/D//2Q==",
      direccion: direccion
    }

    this.http.registrarse(body).subscribe({
      next: (data: any) => {
        console.log(data);
        this.router.navigate(["/login"]);
       },
      error: (error: any) => {
        console.log(error);
        this.error = "Correo ya registrado"
      }

    })
    



  }

}
